### ISSUE TITLE
How to structure repo

### ISSUE THREAD

**Issue by NathanJang** [szimek/heroku-buildpack-ember-cli-without-webserver#2]
How would I structure my repo to use this? Where would I put my backend/frontend relative to each other?

**Comment by szimek** [comment]
I'm using it in https://github.com/cowbell/sharedrop, where the server part is just one file (`index.js`) and so it's in the main folder. I guess it doesn't matter much - e.g. you could put everything in `server` folder - you just need to call your main server file in your [`Procfile`](https://github.com/cowbell/sharedrop/blob/master/Procfile).

**Comment by NathanJang** [comment]
Thanks for the working example! You might want to add a bit more in the README on this.

**Comment by NathanJang** [comment]
Do you use foreman or ember serve during development?

EDIT: `ember build --watch` then `foreman start` :grinning:

**Comment by szimek** [comment]
Currently unfortunately both, however, you could create a second `Procfile` (e.g. `Procfile.dev`) with both `ember serve` and `node server.js` processes and start it using: `foreman start -f Procfile.dev`.

**Comment by NathanJang** [comment]
It's pretty disappointing to have to run 2 separate processes for this, but i guess this is what it's designed for :grin:

**Comment by szimek** [comment]
You can run `ember build --watch` instead of `ember server` if it makes any difference for you :)

**Comment by NathanJang** [comment]
By the way, Heroku now [natively supports multiple buildpacks](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app). You can consider using this instead of the multi-buildpack buildpack.

**Comment by szimek** [comment]
Thanks for the link! I'll update docs as well.

**Comment by NathanJang** [comment]
If you use the native multi, you might run into some issues because this buildpack requires node to have been installed before, but Heroku's guides say that the node buildpack should be run last because that is what starts the server process. I'm still trying to figure it out myself.

**Comment by NathanJang** [comment]
If you look at tonycoco/heroku-buildpack-ember-cli#87 you'll see what I tried to do with the other buildpack, which led to some unexpected issues.
